# Generated by Django 5.2.5 on 2025-09-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_rol_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_medico',
            field=models.BooleanField(default=False),
        ),
    ]
