"""
Django settings for hospital_system project.

Generated by 'django-admin startproject'.

Configuración adaptada para despliegue en Render:
- Manejo seguro de SECRET_KEY y credenciales de email mediante variables de entorno.
- Gestión de archivos estáticos con WhiteNoise.
- Soporte para aplicaciones internas: citas, historial, usuarios, api.
- Integración con Django REST Framework.
"""

from pathlib import Path
import os

# -------------------------------------------------------------------
# Rutas base
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------------------------------------------
# Seguridad
# -------------------------------------------------------------------

# En producción, define SECRET_KEY en las variables de entorno de Render.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "replace-this-with-a-secure-key"  # Solo para desarrollo local
)

# Durante el despliegue inicial en Render puedes dejar DEBUG=True.
# En cuanto todo funcione, cambia a False.
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# En Render, al principio puedes usar '*', luego restringir al dominio real.
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")

# -------------------------------------------------------------------
# Aplicaciones instaladas
# -------------------------------------------------------------------

INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros
    'rest_framework',

    # Apps del proyecto
    'citas',
    'historial',
    'usuarios',
    'api',
]

# Modelo de usuario personalizado
AUTH_USER_MODEL = 'usuarios.Usuario'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# -------------------------------------------------------------------
# Middleware
# -------------------------------------------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise para servir archivos estáticos en producción (Render)
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -------------------------------------------------------------------
# URLs y WSGI/ASGI
# -------------------------------------------------------------------

ROOT_URLCONF = 'hospital_system.urls'

WSGI_APPLICATION = 'hospital_system.wsgi.application'
ASGI_APPLICATION = 'hospital_system.asgi.application'

# -------------------------------------------------------------------
# Plantillas
# -------------------------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Carpeta global de plantillas
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# -------------------------------------------------------------------
# Base de datos
# -------------------------------------------------------------------

# Para empezar en Render usamos SQLite.
# Más adelante puedes migrar a PostgreSQL usando DATABASE_URL.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}

# Ejemplo (comentado) para PostgreSQL en Render:
# import dj_database_url
# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.environ.get("DATABASE_URL"),
#         conn_max_age=600,
#         conn_health_checks=True,
#     )
# }

# -------------------------------------------------------------------
# Internacionalización y zona horaria
# -------------------------------------------------------------------

LANGUAGE_CODE = 'es'

TIME_ZONE = "Europe/Madrid"

USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------------
# Archivos estáticos y media
# -------------------------------------------------------------------

# URL pública de los archivos estáticos
STATIC_URL = '/static/'

# Directorios adicionales de estáticos durante desarrollo
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Directorio donde collectstatic volcará los archivos para producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: comprimir y versionar estáticos
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Archivos subidos por usuarios (si los necesitas)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -------------------------------------------------------------------
# Autenticación y redirecciones
# -------------------------------------------------------------------

LOGIN_URL = '/usuarios/login/'
LOGIN_REDIRECT_URL = '/'          # O 'usuarios/' si quieres redirigir al panel de usuario
LOGOUT_REDIRECT_URL = 'usuarios:login'

# -------------------------------------------------------------------
# Email
# -------------------------------------------------------------------

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Se leen desde variables de entorno en Render para no exponer credenciales
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "Hospital System <no-reply@hospital-system.com>"
)

# -------------------------------------------------------------------
# Django REST Framework
# -------------------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# -------------------------------------------------------------------
# Configuración por defecto de claves primarias
# -------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------------------
# Opcionales de seguridad para producción (cuando DEBUG=False)
# -------------------------------------------------------------------
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
