# Generated by Django 5.2.5 on 2025-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cita_hora_alter_cita_estado_alter_cita_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
